# Gap Analysis Part 1 - Find out the missing date

In [2]:
import pandas as pd
import numpy as np
# import matplotlib.pyplot as plt
from datetime import datetime
# %matplotlib inline

In [4]:
# Load the dataset. This dataset provides the information about busline, date, and how many records in a certain day
# for a specific busline.
gap_count = pd.read_csv('count.csv')
gap_count['Date'] = pd.Series(gap_count['Date'])
gap_count.head()

  Busline      Date  Count
0    Q114  12/31/14    251
1     S57  12/31/14      3
2     B36  12/31/14    227
3      B4  12/31/14    434
4     M22  12/31/14    179

In [5]:
# Figure out how many different buslines are there in the whole dataset.
linelist = list(set(gap_count['Busline']))
print linelist
len(linelist)

['BX15', 'M57', 'S79+', 'B44+', 'M15+', 'S57', 'S56', 'S55', 'S54', 'S53', 'S52', 'S51', 'X10B', 'X27', 'Q15A', 'S59', 'M50', 'Q50', 'Q53', 'Q52', 'Q55', 'Q54', 'M60+', 'Q56', 'B52', 'Q58', 'BX17', 'B54', 'S98', 'Q30', 'Q44+', 'BX11', 'X28', 'Q20B', 'BXM4', 'X30', 'X31', 'BX13', 'M98', 'M42', 'S84', 'X17A', 'BX12', 'BX26', 'S44', 'S46', 'BX8', 'S40', 'S42', 'BX4A', 'S48', 'Q46', 'Q47', 'Q44', 'X38', 'Q42', 'Q43', 'Q40', 'Q41', 'B26', 'B25', 'B24', 'Q104', 'Q48', 'B20', 'B4', 'B6', 'B7', 'B1', 'B2', 'B3', 'S94', 'B12', 'S91', 'B8', 'B9', 'Q103', 'X42', 'M35', 'Q101', 'M31', 'BX12+', 'M5', 'M4', 'M7', 'QM16', 'M1', 'QM10', 'M3', 'M2', 'S78', 'X9', 'Q49', 'M9', 'S74', 'S76', 'QM24', 'B38', 'M66', 'S81', 'B35', 'B36', 'B37', 'QM12', 'B31', 'B32', 'BXM1', 'Q32', 'Q31', 'BX16', 'Q37', 'BX10', 'Q35', 'BXM6', 'BXM9', 'BXM8', 'Q39', 'Q38', 'BX19', 'BX18', 'S90', 'B84', 'BX34', 'B83', 'B82', 'M20', 'M21', 'M22', 'M23', 'BM2', 'BM3', 'BM1', 'S96', 'BM4', 'S89', 'S66', 'X17J', 'M12', 'S62', 'S61', 'M102', 'M103', 'M100', 'M101', 'M106', 'M104', 'QM20', 'Q06', 'Q21', 'Q22', 'Q23', 'Q24', 'Q25', 'Q26', 'B42', 'Q28', 'Q29', 'Q33', 'X68', 'X63', 'BM5', 'X64', 'B57', 'B16', 'B17', 'B14', 'B15', 'Q102', 'B13', 'Q100', 'B11', 'QM18', 'BX28', 'X12', 'BX29', 'BXM18', 'BXM11', 'BXM10', 'M116', 'X8', 'X21', 'Q15', 'S92', 'Q17', 'Q16', 'Q11', 'Q10', 'Q13', 'Q12', 'X2', 'X3', 'X1', 'Q19', 'Q18', 'X4', 'X5', 'B45', 'Q34', 'BXM3', 'QM21', 'QM3', 'QM2', 'QM5', 'QM4', 'QM7', 'QM6', 'Q111', 'Q83', 'Q113', 'Q112', 'BXM7', 'Q114', 'Q84', 'Q85', 'X22', 'Q88', 'B63', 'B62', 'B61', 'B60', 'B67', 'BXM2', 'B65', 'B64', 'B69', 'B68', 'QM17', 'M96', 'M11', 'M10', 'Q08', 'Q09', 'M15', 'S86', 'Q59', 'BX46', 'QM11', 'BX42', 'Q07', 'BX40', 'BX41', 'Q1', 'M72', 'Q3', 'Q2', 'Q5', 'Q4', 'QM8', 'BX24', 'B49', 'M79', 'BX27', 'BX20', 'BX21', 'BX22', 'BX23', 'Q36', 'M86+', 'X14', 'X37', 'B70', 'M14D', 'B74', 'M14A', 'M86', 'X22A', 'M8', 'QM1', 'B103', 'B39', 'M34+', 'Q77', 'Q76', 'BX4', 'Q72', 'Q70', 'B100', 'X7', 'BX39', 'BX38', 'BX36', 'BX35', 'Q27', 'BX33', 'BX32', 'BX31', 'BX30', 'X19', 'X10', 'X11', 'QM15', 'Q20A', 'X15', 'X17', 'BX9', 'B44', 'B47', 'B46', 'B41', 'M34A+', 'B43', 'Q110', 'BX1', 'QM25', 'BX3', 'BX2', 'BX5', 'B48', 'BX7', 'BX6', 'BX41+', 'Q69', 'S93', 'Q64', 'Q65', 'Q66', 'Q67', 'Q60']

318

In [6]:
# Find out the how many different days' records are there included in the dataset.
timelist = list(set(gap_count['Date']))
print timelist
len(timelist)

['1/1/15', '9/2/15', '9/26/15', '9/7/15', '7/14/15', '1/4/15', '9/24/15', '11/20/15', '7/19/15', '1/20/15', '5/2/15', '3/28/15', '9/9/15', '1/11/15', '10/21/15', '3/13/15', '11/2/15', '10/15/15', '3/16/15', '11/14/15', '8/6/15', '1/17/15', '4/28/15', '5/5/15', '1/2/15', '2/2/15', '5/30/15', '10/2/15', '4/9/15', '4/4/15', '6/6/15', '3/1/15', '3/6/15', '5/12/15', '8/10/15', '2/20/15', '11/28/15', '7/15/15', '8/28/15', '8/12/15', '10/20/15', '8/26/15', '4/20/15', '10/25/15', '6/26/15', '9/11/15', '1/29/15', '9/17/15', '3/14/15', '2/28/15', '3/11/15', '1/25/15', '12/2/15', '7/18/15', '10/18/15', '10/31/15', '9/20/15', '9/25/15', '2/10/15', '2/13/15', '5/3/15', '1/21/15', '3/3/15', '1/7/15', '6/29/15', '6/24/15', '6/18/15', '8/19/15', '7/21/15', '6/10/15', '8/18/15', '1/5/15', '1/6/15', '11/18/15', '3/7/15', '5/16/15', '12/8/15', '7/16/15', '11/15/15', '5/13/15', '3/2/15', '4/12/15', '9/13/15', '4/26/15', '7/26/15', '10/29/15', '7/7/15', '7/23/15', '3/25/15', '6/30/15', '10/16/15', '1/16/15', '3/20/15', '5/29/15', '6/12/15', '9/27/15', '11/6/15', '4/17/15', '5/1/15', '1/23/15', '9/22/15', '5/20/15', '3/9/15', '5/18/15', '5/9/15', '7/24/15', '9/5/15', '1/31/15', '5/24/15', '4/29/15', '3/26/15', '6/2/15', '10/30/15', '4/18/15', '1/22/15', '1/10/15', '8/8/15', '7/28/15', '12/7/15', '9/15/15', '9/16/15', '1/3/15', '2/18/15', '4/16/15', '11/16/15', '6/19/15', '11/30/15', '2/16/15', '5/28/15', '8/11/15', '3/24/15', '5/7/15', '8/14/15', '7/4/15', '9/19/15', '10/14/15', '3/19/15', '1/27/15', '8/22/15', '6/7/15', '10/3/15', '7/2/15', '7/9/15', '10/19/15', '11/24/15', '9/21/15', '11/21/15', '12/5/15', '3/5/15', '5/14/15', '4/14/15', '1/30/15', '3/12/15', '8/15/15', '6/1/15', '5/22/15', '5/25/15', '3/22/15', '3/21/15', '10/1/15', '6/28/15', '7/3/15', '11/11/15', '2/15/15', '11/8/15', '3/29/15', '8/17/15', '11/4/15', '9/14/15', '5/17/15', '11/23/15', '4/8/15', '1/8/15', '9/18/15', '2/1/15', '11/26/15', '11/17/15', '8/13/15', '7/1/15', '4/25/15', '8/31/15', '8/29/15', '4/19/15', '11/13/15', '2/27/15', '4/1/15', '10/13/15', '5/27/15', '12/4/15', '2/17/15', '6/14/15', '11/7/15', '4/5/15', '2/21/15', '9/6/15', '9/30/15', '5/10/15', '11/25/15', '8/30/15', '3/18/15', '11/3/15', '3/27/15', '4/27/15', '5/23/15', '3/10/15', '5/26/15', '3/23/15', '8/2/15', '1/18/15', '10/4/15', '7/8/15', '6/23/15', '6/11/15', '12/31/14', '2/4/15', '11/10/15', '4/30/15', '8/4/15', '9/23/15', '11/12/15', '11/27/15', '4/24/15', '7/11/15', '4/13/15', '12/3/15', '2/14/15', '10/6/15', '8/7/15', '2/9/15', '2/23/15', '9/4/15', '2/12/15', '10/27/15', '10/12/15', '7/17/15', '10/9/15', '9/28/15', '8/5/15', '6/16/15', '6/13/15', '7/6/15', '8/3/15', '2/7/15', '10/8/15', '4/3/15', '2/5/15', '7/5/15', '2/19/15', '11/19/15', '8/1/15', '4/2/15', '8/20/15', '12/30/15', '5/19/15', '8/25/15', '9/12/15', '1/9/15', '10/23/15', '4/22/15', '11/9/15', '7/31/15', '7/30/15', '10/22/15', '6/25/15', '6/20/15', '2/25/15', '2/26/15', '9/10/15', '6/15/15', '5/21/15', '8/23/15', '10/7/15', '8/9/15', '12/1/15', '11/5/15', '4/7/15', '2/8/15', '1/19/15', '3/31/15', '5/8/15', '7/29/15', '6/21/15', '1/14/15', '4/11/15', '1/12/15', '4/15/15', '8/21/15', '9/29/15', '4/23/15', '5/31/15', '2/3/15', '1/24/15', '5/6/15', '3/15/15', '7/27/15', '8/16/15', '2/22/15', '6/8/15', '3/17/15', '6/22/15', '7/20/15', '9/8/15', '6/27/15', '10/5/15', '5/15/15', '3/4/15', '1/13/15', '6/4/15', '4/10/15', '4/21/15', '7/10/15', '1/26/15', '5/4/15', '5/11/15', '6/5/15', '12/6/15', '6/3/15', '11/29/15', '1/15/15', '10/24/15', '9/3/15', '2/24/15', '10/26/15', '11/1/15', '2/11/15', '8/27/15', '8/24/15', '6/17/15', '7/25/15', '7/22/15', '10/28/15', '9/1/15', '1/28/15', '4/6/15', '10/17/15', '2/6/15', '6/9/15', '11/22/15', '3/30/15', '10/10/15']

340

In [7]:
days_of_month = [31,28,31,30,31,30,31,31,30,31,30,31]
for i in range(12):
    for j in range(days_of_month[i]):
        tmptimelist = str(i+1) + '/' + str(j+1) + '/15'
        if tmptimelist not in timelist:
            print tmptimelist

3/8/15
7/12/15
7/13/15
10/11/15
12/9/15
12/10/15
12/11/15
12/12/15
12/13/15
12/14/15
12/15/15
12/16/15
12/17/15
12/18/15
12/19/15
12/20/15
12/21/15
12/22/15
12/23/15
12/24/15
12/25/15
12/26/15
12/27/15
12/28/15
12/29/15
12/31/15

### Here show all the missing date in the dataset. That means we do not have any information about the buses' travelling in those date.